config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :update]
  resource :session, only: [:create, :new, :destroy]

  namespace :api, defaults: {format: :json} do
    resources :tasks, only: [:index, :show, :create, :destroy, :update]
    resources :task_types, only: [:index, :show, :create, :destroy, :update]
    resources :avatar, only: [:index, :update]
  end

  root to: "static_pages#root"
end

app/views/layouts/_form.html.erb
<%= auth_token_input %>
<div class="form-group">
  <label>Username</label>
  <input type="text" class="form-control" name="user[username]" value="<%= @user.username %>">
</div>

<div class="form-group">
  <label>Password</label>
  <input type="password" class="form-control" name="user[password]">
</div>

<input type="submit" class="btn btn-primary" data-toggle="modal" data-target="#myModal" value="<%= @button %>">

<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="heartbeat-loader">Loading…</div>
    <br/><br/>
    <span>Your profile is being setup...</span>
  </div>
</div>

app/views/layouts/_guest.html.erb
<form class="guest-auth" action="<%= users_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name=user[username] value="Guest">
    <input type="hidden" name=user[password] value="n3k8c0sap19">
    <input type="submit" data-toggle="modal" data-target="#myModal" value="Sign in as Guest">
</form>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse"
              data-target="#collapse-menu"
              aria-expanded="false">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="collapse-menu">
      <ul class="nav navbar-nav pull-left">
        <!-- <%= link_to "Home", root_url %> -->
        <li><a href="/" onClick={window.location.pathname = '/'}>Home</a></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to("Sign In", new_session_url) %></li>
        <li><%= link_to("Sign Up", new_user_url) %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProductivityRPG</title>
  <link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/pixelated" type="text/css"/>
  <link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- <ul>
    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
        <li>
          <%= error %>
        </li>
      <% end %>
    <% end %>
  </ul> -->

  <div class="container-fluid">
    <!-- <% if signed_in? %>
      <span class="welcome">Greetings, <%= current_user.username %>!</span>
    <% end %> -->
    <%= yield %>
  </div>

  <footer class="container-fluid">
    <div class="row">
      <div class="col-xs-4">
        <a href="https://github.com/BonbonLemon/Productivity-RPG">GitHub Repo</a>
      </div>
      <div class="col-xs-4">
        <a href="http://bonbonlemon.github.io/Profile">About the Creator</a>
      </div>
      <div class="col-xs-4">
        <a href="https://habitica.com/">Original Website (Habitica)</a>
      </div>
    </div>
  </footer>
</body>
</html>